travis:
  secure:
    BINSTAR_TOKEN: DejnmY6Fg+SYofFOG7Ku6qH8jtSOg/KwLGzoPrwz+iTpgi7yLQy2Y/rtmWIl4RG/OOq18+GMo9Ij0ZC8Ndj4jmJNwOyVJNfaPhus9RIKQZwultJkHvQK1CAqTV55n9ibx5O8HsD5tVbMfIkCaInkBmkhCXvaUHVAY+5muEdXd72UqLN4ZrqR+prjqeGuIq4uS15p5w4NGtaeIzOh+OoJOr602CGBBAmFIM2in6fA18hRKA0o55JPEq8Gbc8+l1GAlzKCK5n6Y4UNw/lkTNqvnXkr2zItB+pqqVwVXZyr4sMSnTarfOjj35Hhxz+gi/VwFGcgLcAoaKf0C7xFJAGpSG1GnnkkClNRg81eOsWmEf0asCR0U+Y5c5qsen7wjeMOV7CVKlSdXRqoXRvaCoi1/uI9j5Iibaj46aPsXUiISSu4VAvfXGPPFmDReVDa4gHyCSPRtfI5jW6MPDqYwJcwXeHAecN+2XwtKknjRTk9XY5PsWOY0SS3BkNr0n3YGdvVETnPjMZY7Rey9IxGb9auvMGJ+dkjW1E9+Uq3RbDMyfJxuFtqOlqFtRXLxsakyVod8IUrCWwn+QJSb3Ly+WLr+ry9OP19I2xSp4K8Av8zRrgUrVCHA2e9PEoC6NAHEKswpsj6ZtHEUt3KgFkfQIviE71FilpAdSQf/iHR9Wbj9wQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
